import { BlackCard, WhiteCard, CustomDeck } from './types';

export const OFFICIAL_DECKS: Record<string, { name: string; description: string; blackCards: BlackCard[]; whiteCards: WhiteCard[] }> = {
  base: {
    name: 'Main Deck (Classic)',
    description: 'The definitive collection of absurd, darkly humorous party cards.',
    blackCards: [
      { id: 'b-1', text: 'Why can\'t I sleep at night?', pick: 1, pack: 'base' },
      { id: 'b-2', text: 'What\'s that smell?', pick: 1, pack: 'base' },
      { id: 'b-3', text: 'I got 99 problems but _ ain\'t one.', pick: 1, pack: 'base' },
      { id: 'b-4', text: 'What never fails to liven up the party?', pick: 1, pack: 'base' },
      { id: 'b-5', text: 'What\'s my secret superpower?', pick: 1, pack: 'base' },
      { id: 'b-6', text: 'What is Batman\'s guilty pleasure?', pick: 1, pack: 'base' },
      { id: 'b-7', text: 'TSA guidelines now prohibit _ on airplanes.', pick: 1, pack: 'base' },
      { id: 'b-8', text: 'Next on ESPN2: The World Series of _.', pick: 1, pack: 'base' },
      { id: 'b-9', text: 'Step 1: _. Step 2: _. Step 3: Profit.', pick: 2, pack: 'base' },
      { id: 'b-10', text: 'During his midlife crisis, dad bought _.', pick: 1, pack: 'base' },
      { id: 'b-11', text: 'What will always get you through tough times?', pick: 1, pack: 'base' },
      { id: 'b-12', text: 'What gave me uncontrollable diarrhea?', pick: 1, pack: 'base' },
      { id: 'b-13', text: 'Instead of coal, Santa now gives bad kids _.', pick: 1, pack: 'base' },
      { id: 'b-14', text: 'What broke up my last relationship?', pick: 1, pack: 'base' },
      { id: 'b-15', text: 'My therapist told me to replace my anxiety with _.', pick: 1, pack: 'base' },
      { id: 'b-16', text: 'Before I die, I want to experience _ at least once.', pick: 1, pack: 'base' },
      { id: 'b-17', text: 'What\'s the new Silicon Valley billion-dollar startup idea?', pick: 1, pack: 'base' },
      { id: 'b-18', text: 'Make a sentence: For a good time, call _ and bring _.', pick: 2, pack: 'base' },
      { id: 'b-19', text: 'The secret ingredient in grandma\'s famous casserole is _.', pick: 1, pack: 'base' },
      { id: 'b-20', text: 'What is the real reason aliens refuse to visit Earth?', pick: 1, pack: 'base' },
      { id: 'b-21', text: 'Life was peaceful until _ attacked.', pick: 1, pack: 'base' },
      { id: 'b-22', text: 'I drink to forget _.', pick: 1, pack: 'base' },
      { id: 'b-23', text: 'In a world without rules, all that matters is _.', pick: 1, pack: 'base' },
      { id: 'b-24', text: 'What really caused the fall of the Roman Empire?', pick: 1, pack: 'base' },
      { id: 'b-25', text: 'I never truly understood love until I saw _.', pick: 1, pack: 'base' }
    ],
    whiteCards: [
      { id: 'w-1', text: 'A disappointing birthday party.', pack: 'base' },
      { id: 'w-2', text: 'Overpriced avocado toast.', pack: 'base' },
      { id: 'w-3', text: 'Uncontrollable sobbing.', pack: 'base' },
      { id: 'w-4', text: 'An aggressive flock of Canadian geese.', pack: 'base' },
      { id: 'w-5', text: 'Accidentally replying "Reply All" to 5,000 employees.', pack: 'base' },
      { id: 'w-6', text: 'Spontaneous combustion.', pack: 'base' },
      { id: 'w-7', text: 'Pretending to care about your friend\'s crypto portfolio.', pack: 'base' },
      { id: 'w-8', text: 'Three raccoons in a trench coat.', pack: 'base' },
      { id: 'w-9', text: 'A lukewarm bath full of baked beans.', pack: 'base' },
      { id: 'w-10', text: 'Drinking shampoo because it smelled delicious.', pack: 'base' },
      { id: 'w-11', text: 'Explaining memes to your grandparents.', pack: 'base' },
      { id: 'w-12', text: 'A passive-aggressive email signature.', pack: 'base' },
      { id: 'w-13', text: 'An uncomfortably long hug.', pack: 'base' },
      { id: 'w-14', text: 'Eating an entire pizza in bed at 3 AM.', pack: 'base' },
      { id: 'w-15', text: 'The WiFi dropping during an important meeting.', pack: 'base' },
      { id: 'w-16', text: 'A majestic bald eagle wearing sunglasses.', pack: 'base' },
      { id: 'w-17', text: 'My crippling existential dread.', pack: 'base' },
      { id: 'w-18', text: 'Screaming into a pillow.', pack: 'base' },
      { id: 'w-19', text: 'A slightly suspicious hot dog.', pack: 'base' },
      { id: 'w-20', text: 'Stepping on a Lego barefoot.', pack: 'base' },
      { id: 'w-21', text: 'Fake coughing to get out of social obligations.', pack: 'base' },
      { id: 'w-22', text: 'A surprisingly athletic sumo wrestler.', pack: 'base' },
      { id: 'w-23', text: 'Unsolicited life advice from a stranger.', pack: 'base' },
      { id: 'w-24', text: 'A mysterious rash.', pack: 'base' },
      { id: 'w-25', text: 'Falling asleep on the toilet.', pack: 'base' },
      { id: 'w-26', text: 'Awkward elevator silence.', pack: 'base' },
      { id: 'w-27', text: 'A cursed ventriloquist dummy.', pack: 'base' },
      { id: 'w-28', text: 'Buying things you can\'t afford to impress people you don\'t like.', pack: 'base' },
      { id: 'w-29', text: 'An overwhelming urge to dance like nobody is watching.', pack: 'base' },
      { id: 'w-30', text: 'Glitter in places glitter should never be.', pack: 'base' },
      { id: 'w-31', text: 'A microwave that beeps too loudly at 2 AM.', pack: 'base' },
      { id: 'w-32', text: 'A aggressively loud yawn.', pack: 'base' },
      { id: 'w-33', text: 'Holding in a sneeze so hard your ears pop.', pack: 'base' },
      { id: 'w-34', text: 'Walking into a room and completely forgetting why you went in there.', pack: 'base' },
      { id: 'w-35', text: 'Finding $20 in your winter coat pocket.', pack: 'base' }
    ]
  },
  geek: {
    name: 'Tech & Dev Pack',
    description: 'Code crashes, AI overloads, stack overflow copy-pastes, and dev jokes.',
    blackCards: [
      { id: 'gb-1', text: 'What caused the production server to crash at 5 PM on a Friday?', pick: 1, pack: 'geek' },
      { id: 'gb-2', text: 'AI will eventually replace doctors, lawyers, and _.', pick: 1, pack: 'geek' },
      { id: 'gb-3', text: 'My pull request was rejected because of _.', pick: 1, pack: 'geek' },
      { id: 'gb-4', text: 'Why did the junior developer start crying?', pick: 1, pack: 'geek' },
      { id: 'gb-5', text: 'In our next agile sprint, we are prioritizing _.', pick: 1, pack: 'geek' },
      { id: 'gb-6', text: 'The newest LLM model is trained exclusively on _.', pick: 1, pack: 'geek' },
      { id: 'gb-7', text: 'Pair programming with _ went horribly wrong.', pick: 1, pack: 'geek' },
      { id: 'gb-8', text: 'I replaced my entire engineering team with _.', pick: 1, pack: 'geek' }
    ],
    whiteCards: [
      { id: 'gw-1', text: 'Pushing straight to main with git push --force.', pack: 'geek' },
      { id: 'gw-2', text: 'Stack Overflow being down for 10 minutes.', pack: 'geek' },
      { id: 'gw-3', text: 'An infinite recursive loop in production.', pack: 'geek' },
      { id: 'gw-4', text: 'A sentient toaster demanding root privileges.', pack: 'geek' },
      { id: 'gw-5', text: 'Deleting the production database with no backups.', pack: 'geek' },
      { id: 'gw-6', text: 'A 50,000-line merge conflict.', pack: 'geek' },
      { id: 'gw-7', text: 'Uncommenting code you wrote 6 months ago that says // DO NOT TOUCH.', pack: 'geek' },
      { id: 'gw-8', text: 'An AI chatbot that learned existential depression.', pack: 'geek' },
      { id: 'gw-9', text: 'A mechanical keyboard so loud it violates the Geneva Convention.', pack: 'geek' },
      { id: 'gw-10', text: 'Paying $40,000 in unexpected AWS egress fees.', pack: 'geek' },
      { id: 'gw-11', text: 'Turning it off and on again.', pack: 'geek' },
      { id: 'gw-12', text: 'Closing 94 open Chrome tabs all at once.', pack: 'geek' },
      { id: 'gw-13', text: 'Debugging with console.log("here 1", "here 2", "HELP").', pack: 'geek' },
      { id: 'gw-14', text: 'A dark mode toggle that blinds the user anyway.', pack: 'geek' },
      { id: 'gw-15', text: 'Coffee, pure panic, and caffeine pills.', pack: 'geek' }
    ]
  },
  absurd: {
    name: 'Absurd & Chaos Pack',
    description: 'Bizarre, hilarious, and surreal cards.',
    blackCards: [
      { id: 'ab-1', text: 'The prophecy foretold that the chosen one would arrive bearing _.', pick: 1, pack: 'absurd' },
      { id: 'ab-2', text: 'Scientists have discovered that the universe is made entirely of _.', pick: 1, pack: 'absurd' },
      { id: 'ab-3', text: 'What is hiding in my walls?', pick: 1, pack: 'absurd' },
      { id: 'ab-4', text: 'My secret weapon in any street fight is _.', pick: 1, pack: 'absurd' },
      { id: 'ab-5', text: 'Before battle, Vikings would consume _ for strength.', pick: 1, pack: 'absurd' }
    ],
    whiteCards: [
      { id: 'aw-1', text: 'A hot dog launcher with laser guidance.', pack: 'absurd' },
      { id: 'aw-2', text: 'A choir of screaming opossums.', pack: 'absurd' },
      { id: 'aw-3', text: 'Cursed spaghetti that whispers ancient Latin.', pack: 'absurd' },
      { id: 'aw-4', text: 'A swarm of heavily armed hamsters.', pack: 'absurd' },
      { id: 'aw-5', text: 'An aggressively friendly clown in your rear-view mirror.', pack: 'absurd' },
      { id: 'aw-6', text: 'Liquid cheese pumped directly into your veins.', pack: 'absurd' },
      { id: 'aw-7', text: 'A disco ball that hypnotizes pigeons.', pack: 'absurd' },
      { id: 'aw-8', text: 'Extreme unicycling while juggling live flamingos.', pack: 'absurd' },
      { id: 'aw-9', text: 'A time traveler who just wants a decent taco.', pack: 'absurd' },
      { id: 'aw-10', text: 'A golden statue of a dancing potato.', pack: 'absurd' }
    ]
  }
};
